const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirts',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality imported product',
        },
        {
            _id: '2',
            name: 'Jeans Dress Pants',
            category: 'Pants',
            image: '/images/p2.jpg',
            price: 135,
            brand: 'Jeans',
            rating: 4,
            numReviews: 12,
            description: 'Best quality comfortable pants',
        },
        {
            _id: '3',
            name: 'Adidas boots',
            category: 'Shoes',
            image: '/images/p3.jpg',
            price: 110,
            brand: 'Adidas',
            rating: 5,
            numReviews: 16,
            description: 'best reviewed shoes',
        },
        {
            _id: '4',
            name: 'Gucci hand bag',
            category: 'hand bag',
            image: '/images/p4.jpg',
            price: 90,
            brand: 'Gucci',
            rating: 3.5,
            numReviews: 5,
            description: 'Medium quality product',
        },
        {
            _id: '5',
            name: 'Rolax hand watch',
            category: 'Watch',
            image: '/images/p5.jpg',
            price: 250,
            brand: 'Rolax',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality imported product',
        },
        {
            _id: '6',
            name: 'CA cricket bat',
            category: 'cricket',
            image: '/images/p6.jpg',
            price: 120,
            brand: 'CA',
            rating: 5,
            numReviews: 20,
            description: 'High quality non-breakable product',
        },        
    ]
}

export default data;